version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/spedevdb
      - JWT_SECRET=superSecretChiffre123 # Enlever cette ligne et ajouter la variable
        # d'environnement dans le fichier .env a la racine du projet
        # (voir le fichier .env.example)
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001/api
    depends_on:
      - backend

volumes:
  mongo_data:
